<p>
    <h2>
    <?php  echo $title?>
    </h2>
</p>

<div class="container bg-warning col-3 py-3">
    <div class="card card-login mx-auto mt-5">
        <div class="card-header"><?php  echo $title?></div>
        <div class="card-body">
            <form action="register" method="post">
                <div class="form-group">
                    <label for="">Логин:</label>
                    <input class="form-control" type="text" name="login">
                </div>
                <div class="form-group">
                    <label for="">Пароль:</label>
                    <input class="form-control" type="password" name="password">
                </div>
                <button class="btn btn-small btn-primary btn-block mt-3" type="submit">Регистрация</button>
            </form>
        </div>
    </div>
</div>

