<header>
    <div class="container">
        <div class="row">
            <div class="header mt-2 col-6">
                <h4>ПРОЕКТ SF-25.9</h4>
            </div>

            <div class="col-6">

                <nav class="navbar navbar-expand-lg navbar-light">
                    <div class="container-fluid">
                        <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Переключатель навигации">
                            <span class="navbar-toggler-icon"></span>
                        </button>
                        <div class="collapse navbar-collapse" id="navbarSupportedContent">
                            <ul class="navbar-nav ms-auto mb-2 mb-lg-0">

                                <li class="nav-item">
                                    <a class="nav-link active" aria-current="page" href="/">Главная</a>
                                </li>

                                <?php if (isset($_SESSION['account']['id'])): ?>
                                <li class="nav-item">
                                    <a class="nav-link" href="/logout">Выход</a>
                                </li>

                                <?php elseif (!isset($_SESSION['account']['id'])): ?>
                                <li class="nav-item">
                                    <a class="nav-link" aria-current="page" href="/register">Регистрация</a>
                                </li>
                                <li class="nav-item">
                                    <a class="nav-link" href="/login">Вход</a>
                                </li>
                                <?php endif; ?>
                            </ul>

                        </div>
                    </div>
                </nav>
            </div>
        </div>
    </div>

</header>